AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - lib/templates/**/*
    - vendor/**/*

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Lint/EndAlignment:
  AlignWith: variable
  SupportedStyles:
    - keyword
    - variable

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation
